import asyncio
import json
import os
import time
from main import run_audit

# Define diverse test cases
TEST_STORES = [
    {
        "type": "Modern Supermarket",
        "url": "https://www.google.com/maps/place/Reliance+Fresh/@19.0760,72.8777,15z" 
    },
    {
        "type": "Kirana Store",
        "url": "https://www.google.com/maps/place/Ganesh+Kirana+Store/@19.1176,72.8833,17z"
    },
    {
        "type": "Roadside Tea Stall",
        "url": "https://www.google.com/maps/place/Chai+Point/@19.0759,72.8777,15z"
    }
]

async def run_batch_test():
    print("🧪 Starting Batch Diversity Test Phase...")
    batch_results = []
    
    for store in TEST_STORES:
        print(f"\n{'='*50}")
        print(f"🏢 TESTING STORE TYPE: {store['type']}")
        print(f"📍 URL: {store['url']}")
        print(f"{'='*50}")
        
        start_time = time.time()
        try:
            # Run the audit (main.py will save audit_report.json)
            await run_audit(store['url'])
            
            # Read the report generated by main.py
            if os.path.exists("audit_report.json"):
                with open("audit_report.json", "r") as f:
                    report = json.load(f)
                    
                duration = round(time.time() - start_time, 2)
                print(f"✅ Completed {store['type']} in {duration}s")
                
                batch_results.append({
                    "store_type": store['type'],
                    "url": store['url'],
                    "status": "Success",
                    "duration_s": duration,
                    "summary": f"Analyzed {report.get('total_images_analyzed', 0)} images."
                })
                
                # Copy to a unique filename for this batch
                safe_name = store['type'].lower().replace(" ", "_")
                os.rename("audit_report.json", f"audit_{safe_name}.json")
            else:
                print(f"⚠️ No report generated for {store['type']}")
                
        except Exception as e:
            print(f"❌ Failed {store['type']}: {e}")
            batch_results.append({
                "store_type": store['type'],
                "url": store['url'],
                "status": "Failed",
                "error": str(e)
            })

    # Final Batch Summary
    print(f"\n{'#'*50}")
    print("📊 BATCH TEST SUMMARY")
    print(f"{'#'*50}")
    
    with open("batch_summary.json", "w") as f:
        json.dump(batch_results, f, indent=4)
        
    for res in batch_results:
        status_icon = "✅" if res['status'] == "Success" else "❌"
        print(f"{status_icon} {res['store_type']}: {res['status']} {res.get('summary', '')}")

    print(f"\nDetailed results saved to batch_summary.json and individual audit_*.json files.")

if __name__ == "__main__":
    asyncio.run(run_batch_test())
